---
- name: 8.1. Ensure ServerTokens is Set to Prod or ProductOnly
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: "^#ServerName"
    line: 'ServerTokens Prod'
  tags:
    - automated
    - section08.1

- name: 8.2 Ensure ServerSignature Is Not Enabled
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: "^#ServerName"
    line: 'ServerSignature Off'
  tags:
    - automated
    - section08.2