---
# content level 1 and 2
- name: 4.1. Ensure Access to OS Root Directory Is Denied By Default
  shell: perl -ne 'print if /^ *<Directory *\//i .. /<\/Directory/i' {{apache_conf_dir}}/conf/httpd.conf | grep "Require all denied" > Check/Access_to_OS_Root_Directory_Is_Denied.txt
  tags:
    - automated
    - section04.1

- name: 4.2. Ensure Appropriate Access to Web Content Is Allowed
  shell: echo  "\nManual Check Required\n" > Check/Appropriate_Access_to_Web_Content_Is_Allowed.txt
  tags:
    - automated
    - section04.2

- name: 4.3. Ensure OverRide Is Disabled for the OS Root Directory
  shell: perl -ne 'print if /^ *<Directory *\//i .. /<\/Directory/i' {{apache_conf_dir}}/conf/httpd.conf | grep "AllowOverride none" > Check/OverRide_Is_Disabled_for_the_OS_Root_Directory.txt
  tags:
    - automated
    - section04.3

- name: 4.4. Ensure OverRide Is Disabled for All Directories
  shell: grep -i AllowOverride {{apache_conf_dir}}/conf/httpd.conf > Check/OverRide_Is_Disabled_for_All_Directories.txt
  tags:
    - automated
    - section04.4